name: dammit databases
description: Install Dammit databases for Annotation 
authors:
  - N. Tessa Pierce
output:
  - downloaded and formatted dammit databases 
documentation:
  - "`dib-lab.github.io/dammit <http://dib-lab.github.io/dammit>_`"
