name: bowtie2 align
description: |
  Map reads to a nucleotide reference
authors:
  - Johannes Köster, N. Tessa Pierce
input:
  - fastq files
  - indexed nucleotide fasta
output:
  - mapped reads (BAM format)
citations:
  - "Langmead B, Salzberg S. Fast gapped-read alignment with Bowtie 2. Nature Methods. 2012, 9:357-359"
