name: paladin align
description: |
Align nucleotide reads to a protein fasta file (that has been indexed with paladin index)

PALADIN is a protein sequence alignment tool designed for the accurate functional    characterization of metagenomes.

Westbrook, Anthony et al. 'PALADIN: protein alignment for functional profiling whole   metagenome shotgun data' Bioinformatics (Oxford, England) vol. 33,10 (2017): 1473-1478

authors:
  - N. Tessa Pierce
input:
  - nucleotide reads (fastq)
  - index protein fasta file
output:
  - mapped reads (BAM format) 
